sudo: false
dist: trusty
language: python
python:
  - "2.7"
notifications:
  email: false
env:
  - PATH="${PATH}:${HOME}/google-cloud-sdk/bin" PYTHONPATH="${PYTHONPATH}:${HOME}/google-cloud-sdk/platform/google_appengine"

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
install:
  # If the SDK is not already cached, download it and unpack it
  - |
    if [ ! -d ${HOME}/google-cloud-sdk ]; then
       curl https://sdk.cloud.google.com | bash;
    fi
  - ls ${HOME}/google-cloud-sdk/google/appengine/ext || ls ${HOME}/
  - |
    if [ ! -d ${HOME}/google-cloud-sdk/google/appengine/ext ]; then
       ${HOME}/google-cloud-sdk/bin/gcloud components install app-engine-python-extras;
    fi
  - pip install coveralls
  - pip install -r dev_requirements.txt
script:
    ./build
after_success:
    coveralls
