sudo: false
dist: trusty
language: python
python:
- "2.7"
notifications:
  email: false
env:
- PATH="${PATH}:${HOME}/google-cloud-sdk/bin" PYTHONPATH="${PYTHONPATH}:${HOME}/google-cloud-sdk/platform/google_appengine" CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
before_install:
- openssl aes-256-cbc -K $encrypted_9a87c6a77a8b_key -iv $encrypted_9a87c6a77a8b_iv
  -in client-secret.json.enc -out client-secret.json -d
install:
- |
  if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
     rm -rf ${HOME}/google-cloud-sdk;
     curl https://sdk.cloud.google.com | bash;
  fi
- source "${HOME}/google-cloud-sdk/path.bash.inc"
- gcloud version
- |
  if [ ! -d ${HOME}/google-cloud-sdk/google/appengine/ext ]; then
     gcloud components install app-engine-python-extras;
  fi
- pip install coveralls
- pip install -r dev_requirements.txt
script: "./build"
after_success: coveralls
deploy:
  provider: gae
  keyfile: client-secret.json
  project: isitketo-191301
  config: app/app.yaml
  skip_cleanup: true
