#!/bin/bash
#
# Build steps to validate the KetoHub Offline Scraper.

# Exit build script on first failure
set -e

# Echo commands to stdout.
set -x

# Delete pyc files from previous builds.
find . -name "*.pyc" -delete

# Run unit tests and calculate code coverage.
coverage run \
  --source app \
  -m unittest discover

# Check that source has correct formatting.
yapf --diff --recursive --style google ./ --exclude=./third_party/*

# Run static analysis for Python bugs/cruft.
pyflakes app/*.py tests/*.py

# Check docstrings for style consistency.
PYTHONPATH=$PYTHONPATH:$(pwd)/third_party/docstringchecker \
  pylint --reports=n app tests

if [ "$1" != "--quick" ]; then
  pushd e2e;
  docker-compose up -d;
  python e2e.py \
    --selenium_hub_url=http://127.0.0.1:4444/wd/hub \
    --app_url=http://isitketo_dev:8080;
  popd;
fi
