version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - isitketo_dev
  isitketo_dev:
    build:
      context: .
      dockerfile: Dockerfile.isitketo_dev
    expose:
      - "8080"
    ports:
      - "8000:8000"
