FROM google/cloud-sdk:160.0.0

WORKDIR app/

EXPOSE 8080
EXPOSE 8000

CMD ${HOME}/google-cloud-sdk/bin/dev_appserver.py \
  --enable_host_checking False \
  --host 0.0.0.0 \
  --port 8080 \
  --admin_host 0.0.0.0 \
  --admin_port 8000 \
  --datastore_path /testdata/isitketo_dev_datastore \
  app.yaml
